services:
  - type: web
    name: telebot
    env: python
    plan: free   # or starter/pro depending on your account
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: LOG_CHANNEL_ID
        sync: false
